#!/bin/bash
set -euxo pipefail

# To get the assembly:
riscv32-unknown-elf-gcc -S -o fib.s fib.c
# To get the ELF:
riscv32-unknown-elf-gcc -g -e _start -nostartfiles fib.c -o fib
set +e
qemu-riscv32-static fib
echo $?

qemu-riscv32-static -g 1234 ../asm/fib
