#!/bin/bash
set -euxo pipefail

# To get the assembly:
riscv64-unknown-linux-gnu-gcc -S -o fib_print.s fib_print.c

# To get the ELF:
# riscv32-unknown-elf-gcc -march=rv32im -g -e _start -nostartfiles fib.c -o fib
# riscv32-unknown-elf-gcc -march=rv32im -mabi=ilp32 -g fib_print.c -o fib_print
# riscv64-unknown-elf-gcc -march=rv64im -mabi=lp64 -g fib_print.c -o fib_print
riscv64-unknown-linux-gnu-gcc -g fib_print.c -o fib_print

# riscv32-unknown-linux-gnu-gcc -march=rv32im -mabi=ilp32 -g fib_print.c -o fib_print
# set +e
# qemu-riscv32-static fib
# echo $?

# qemu-riscv64-static -g 1234 fib_print
qemu-riscv64-static -g 1234 -L /opt/riscv64-gnu-toolchain-glibc-bin/sysroot/ fib_print
