#!/bin/bash
set -euxo pipefail

# docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

docker run --privileged --rm tonistiigi/binfmt --install all


ls /proc/sys/fs/binfmt_misc
# Should show something like
# qemu-aarch64  qemu-arm  qemu-mips64  qemu-mips64el  qemu-ppc64le  qemu-riscv64  qemu-s390x  register  status

# Note: if this step fails, but the previous one succeeded,
# you might have to restart your kernel, ie reboot your machine.
docker run --rm -it --platform linux/riscv64 riscv64/ubuntu bash
