#!/bin/bash
set -euxo pipefail
# TODO: Dockerify? in normal linux?
# Probably do add a dev container in vscode?

# on eg Arch Linux you can install https://aur.archlinux.org/packages/riscv-gnu-toolchain-bin
# to get riscv64-unknown-elf-as and riscv64-unknown-elf-ld
# See https://github.com/riscv-collab/riscv-gnu-toolchain for other platforms.
riscv64-unknown-elf-as -o asm/sample.o asm/sample.s
riscv64-unknown-elf-ld -o asm/sample asm/sample.o

set +e
qemu-riscv64-static asm/sample
echo $?
